language: ruby
arch:
  - amd64
  - ppc64le
before_install:
  - "echo 'gem: --no-rdoc --no-ri' > ~/.gemrc"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - rbx-3
  - truffleruby
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: truffleruby
    - rvm: truffleruby-head
  fast_finish: true
script: bundle exec rake
